stages:
  - build
  - test

# Build job voor Windows
build-job:
  stage: build
  script:
    - Write-Host "Compiling the Mancala project..."
    - mvn compile

# Test job voor Windows
test-job:
  stage: test
  script:
    - Write-Host "Running unit tests..."
    - mvn test